#!/usr/bin/env node
/**
 * generate_script.js
 *
 * Regenerates conversation-script.md from scenarios.js + synthetic-data.js.
 * Run directly:    node generate_script.js
 * Auto-invoked by: python3 server.py (on every startup)
 *
 * Update this generator when the shape of scenarios.js or synthetic-data.js changes.
 */

"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT = __dirname;

// Load browser-targeted files by mocking window/global
global.window = {};
eval(fs.readFileSync(path.join(ROOT, "scenarios.js"), "utf8"));        // sets window.DEMO_SCENARIOS
eval(fs.readFileSync(path.join(ROOT, "synthetic-data.js"), "utf8"));   // sets window.SYNTHETIC_KNOWLEDGE

const SCENARIOS = window.DEMO_SCENARIOS;
const KNOWLEDGE = window.SYNTHETIC_KNOWLEDGE;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const out = [];

function line(s = "")  { out.push(s); }
function h(n, t)       { line("#".repeat(n) + " " + t); line(); }
function ul(items)     { items.forEach(i => line("- " + i)); line(); }
function tableRow(cells, sep = false) {
  line("| " + cells.join(" | ") + " |");
  if (sep) line("| " + cells.map(() => "---").join(" | ") + " |");
}
function hr()          { line("---"); line(); }
function blockquote(t) { line("> " + t); line(); }
function badge(label, value, color = "blue") {
  // plain text fallback (GitHub renders these correctly)
  return `**${label}:** ${value}`;
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

const generated = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";

line("# Northlake Health Voice Agent — Conversation Script");
line();
blockquote(
  "Auto-generated from `scenarios.js` and `synthetic-data.js`.\n" +
  "> Regenerated on every `python3 server.py` startup.\n" +
  "> Do not edit this file by hand — update the source files instead."
);
line(`_Generated: ${generated}_`);
line();
hr();

// ---------------------------------------------------------------------------
// Shared validation protocol
// ---------------------------------------------------------------------------

h(2, "Validation Protocol");

const vp = KNOWLEDGE.shared.validationProtocol;
line(`**Prompt:** "${vp.prompt}"`);
line();
line(`**Success phrase:** "${vp.successPhrase}"`);
line();
line(`**Failure route:** ${vp.failureRoute}`);
line();
line("**Accepted demo values:**");
line();
tableRow(["Name", "Date of Birth", "Masked acknowledgement"], true);
vp.acceptedDemoValues.forEach(v => tableRow([v.name, v.dateOfBirth, v.masked]));
line();

// ---------------------------------------------------------------------------
// Safety guardrails
// ---------------------------------------------------------------------------

h(2, "Safety Guardrails");
ul(KNOWLEDGE.shared.guardrails);

// ---------------------------------------------------------------------------
// Approved facilities
// ---------------------------------------------------------------------------

h(2, "Approved Facilities");
tableRow(["Name", "Type", "Address", "Hours", "Parking"], true);
KNOWLEDGE.shared.facilities.forEach(f =>
  tableRow([f.name, f.type, f.address, f.hours, f.parking])
);
line();

// ---------------------------------------------------------------------------
// Shared operational data
// ---------------------------------------------------------------------------

h(2, "Approved Callback Windows");
ul(KNOWLEDGE.shared.callbackWindows);

h(2, "Escalation Triggers");
ul(KNOWLEDGE.shared.escalationReasons);

hr();

// ---------------------------------------------------------------------------
// Per-scenario sections
// ---------------------------------------------------------------------------

Object.entries(SCENARIOS).forEach(([key, scenario]) => {
  h(2, `Scenario: ${scenario.label}`);
  line(`**${scenario.title}**`);
  line();
  line(`> _"${scenario.hook}"_`);
  line();

  line(`**Summary:** ${scenario.summary}`);
  line();
  line(`**Talk track:**`);
  line(`> ${scenario.talkTrack}`);
  line();
  line(`**Close:** _"${scenario.close}"_`);
  line();

  h(3, "Screen captions");
  ul(scenario.captions);

  // -------------------------------------------------------------------------
  // Beat-by-beat script
  // -------------------------------------------------------------------------

  h(3, "Beat-by-beat script");
  tableRow(["Time", "Scene", "Who", "Type", "Dialogue / Action", "Metrics (contained / wait / lang)", "Action packet"], true);

  scenario.script.forEach(beat => {
    const metrics = beat.metrics ? beat.metrics.join(" / ") : "—";
    const packet  = beat.packet  ? beat.packet.join("; ")   : "—";
    const tag     = beat.tag     ? ` \\[**${beat.tag}**\\]` : "";
    const text    = beat.text + tag;
    tableRow([beat.time, beat.scene, beat.who, beat.type, text, metrics, packet]);
  });

  line();

  // -------------------------------------------------------------------------
  // Scenario-specific knowledge
  // -------------------------------------------------------------------------

  const sk = KNOWLEDGE[key];
  if (!sk) return;

  h(3, "Approved FAQ");
  tableRow(["Topic", "Approved answer"], true);
  sk.approvedFaq.forEach(faq => tableRow([faq.topic, faq.answer]));
  line();

  h(3, "Action packet template");
  ul(sk.actionPacketTemplate);

  h(3, "Demo personas");
  sk.personas.forEach(persona => {
    line(`#### ${persona.name}`);
    line();
    line(`| Field | Value |`);
    line(`| --- | --- |`);
    line(`| Scenario | ${persona.scenario} |`);
    line(`| Date of birth | ${persona.dateOfBirth} |`);
    line(`| Opening utterance | _"${persona.startingUtterance}"_ |`);
    line();
    line("**Approved facts for this persona:**");
    line();
    ul(persona.approvedFacts);
  });

  hr();
});

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

const outputPath = path.join(ROOT, "conversation-script.md");
fs.writeFileSync(outputPath, out.join("\n"), "utf8");
console.log("conversation-script.md updated (" + out.length + " lines)");
