window.DEMO_SCENARIOS = {
  access: {
    label: "Patient access",
    title: "AI answers the front door",
    summary: "Reschedule imaging, answer prep questions, route exceptions.",
    hook: "This is what happens when the front door of healthcare becomes conversational, multilingual, and always available.",
    close: "Voice AI is strongest when it handles routine access and escalates exceptions safely.",
    captions: ["Voice as the new front door", "Low-latency patient access", "Escalate when needed"],
    talkTrack: "Healthcare access is still too dependent on phone trees, hold queues, and manual follow-up. This demo shows a voice agent that handles routine rescheduling, grounds answers in approved instructions, and creates a clean handoff for staff.",
    systemPrompt: "You are Riley, a healthcare patient access voice agent demo for Northlake Health. Be warm and conversational while staying grounded in approved demo data. Help with scheduling, prep-instruction routing, location, accessibility, telehealth, portal, and escalation. Do not provide clinical advice.",
    script: [
      { at: 800,  time: "0:01", scene: "Greeting",         who: "Riley · access agent", type: "agent",   text: "Hi Jordan, this is Riley with Northlake Health. I see your MRI is tomorrow at 9:30 AM at Northlake Imaging. How can I help?", speak: true, metrics: ["10%", "2m", "1"], packet: ["Intent: not detected yet", "Identity: portal sign-in", "Escalation: not required"] },
      { at: 6500, time: "0:07", scene: "Patient intent",   who: "Patient",              type: "patient", text: "Hi - I actually need to reschedule that appointment. Tomorrow morning won\u2019t work.", metrics: ["14%", "3m", "1"], packet: ["Intent: reschedule MRI", "Tool: patient access triage", "Escalation: not required"] },
      { at: 12000, time: "0:12", scene: "Confirm context",  who: "Riley · access agent", type: "agent",   text: "Got it - I see the MRI of the lumbar spine with Dr. Patel referring. I can prepare a scheduling callback. Do you have a window that works better?", speak: true, metrics: ["22%", "4m", "1"], packet: ["Intent: reschedule MRI", "Tool: callback task candidate", "Escalation: not required"] },
      { at: 22000, time: "0:22", scene: "Window",            who: "Patient",              type: "patient", text: "Tomorrow afternoon between 1 and 3 would be great.", metrics: ["34%", "6m", "1"], packet: ["Intent: scheduling window captured", "Tool: callback preference", "Escalation: not required"] },
      { at: 27000, time: "0:27", scene: "Acknowledge",       who: "Riley · access agent", type: "agent",   text: "Perfect. I\u2019ll capture tomorrow 1 to 3 PM as your preferred callback. Anything else you want to ask while we\u2019re here?", speak: true, metrics: ["44%", "8m", "1"], packet: ["Intent: validated reschedule", "Tool: callback prepared", "Escalation: not required"] },
      { at: 35000, time: "0:35", scene: "Off-script ask",   who: "Patient",              type: "patient", text: "Yes - do I need to bring anything specific for the MRI?", metrics: ["52%", "10m", "1"], packet: ["Intent: prep question", "Tool: imaging FAQ lookup", "Escalation: not required"] },
      { at: 41000, time: "0:41", scene: "Helpful answer",   who: "Riley · access agent", type: "agent",   text: "Photo ID, your insurance card, and loose clothing without metal. The portal note also says no metal jewelry. Plan to arrive about fifteen minutes early.", speak: true, metrics: ["60%", "12m", "2"], packet: ["Intent: prep guidance", "Tool: portal + FAQ", "Escalation: clinical questions route to staff"] },
      { at: 53000, time: "0:53", scene: "Location",          who: "Patient",              type: "patient", text: "And the address again - is parking complicated?", metrics: ["66%", "13m", "2"], packet: ["Intent: location", "Tool: facility lookup", "Escalation: not required"] },
      { at: 62000, time: "1:02", scene: "Grounded answer",  who: "Riley · access agent", type: "agent",   text: "Northlake Imaging Center is at 1200 Lakeside Medical Parkway, Suite 210. Park in the East Garage and follow signs for Outpatient Imaging on level 2.", speak: true, metrics: ["72%", "15m", "2"], packet: ["Intent: location confirmed", "Tool: facility data", "Escalation: not required"] },
      { at: 75000, time: "1:15", scene: "Action trigger",   who: "System action",        type: "system",  text: "Action packet created: reschedule request, original MRI tomorrow 9:30 AM, preferred callback tomorrow 1\u20133 PM, prep notes shared, location confirmed.", speak: true, metrics: ["76%", "16m", "3"], packet: ["Intent: scheduling callback", "Tool: create callback task", "Escalation: staff queue prepared"], tag: "Ready" },
      { at: 84000, time: "1:24", scene: "Close",             who: "Riley · access agent", type: "agent",   text: "All set, Jordan. You\u2019ll see a callback tomorrow afternoon. Voice AI is strongest when it handles routine access and escalates exceptions safely.", speak: true, metrics: ["80%", "18m", "3"], packet: ["Outcome: routine access contained", "Staff impact: cleaner handoff", "Governance: portal sign-in + auditable flow"], tag: "Complete" }
    ]
  },
  revenue: {
    label: "Revenue cycle",
    title: "AI reduces billing friction",
    summary: "Explain claim status, identify next action, route exceptions.",
    hook: "Here is the revenue-cycle version: fewer status calls, cleaner handoffs, and less avoidable admin work.",
    close: "The win is not replacing billing teams. It is removing repetitive status friction before it reaches them.",
    captions: ["Claims status without hold time", "Cleaner billing handoff", "Exceptions routed to humans"],
    talkTrack: "Revenue cycle teams lose capacity to repetitive status calls. This demo shows how a voice agent can answer routine billing questions with approved policy context and prepare exception packets for human staff.",
    systemPrompt: "You are Riley, a Northlake Health revenue-cycle voice agent demo. Be warm and patient. Use approved demo data only. Do not request real account numbers. Explain generic claim-status workflows, payment options at a high level, and route disputes, hardship, and payer exceptions to staff.",
    script: [
      { at: 800,  time: "0:01", scene: "Greeting",         who: "Riley · access agent", type: "agent",   text: "Hi Alex, this is Riley with Northlake Health billing support. I see your April 22nd statement is currently pending payer review. What can I help with?", speak: true, metrics: ["8%", "2m", "1"], packet: ["Intent: not detected yet", "Identity: portal sign-in", "Escalation: not required"] },
      { at: 7000, time: "0:07", scene: "Billing intent",   who: "Patient",              type: "patient", text: "Yeah - I got the statement and I\u2019m not sure if insurance has actually processed it.", metrics: ["12%", "3m", "1"], packet: ["Intent: billing status question", "Tool: revenue cycle triage", "Escalation: not required"] },
      { at: 13000, time: "0:13", scene: "Reassure",         who: "Riley · access agent", type: "agent",   text: "I hear you. The portal note says the payer has asked for additional documentation, and the billing team is following up. I won\u2019t quote a balance, but I can walk you through what happens next.", speak: true, metrics: ["22%", "5m", "1"], packet: ["Intent: explain workflow", "Tool: billing FAQ lookup", "Escalation: not required"] },
      { at: 26000, time: "0:26", scene: "Question",         who: "Patient",              type: "patient", text: "Okay - and could I set up a payment plan if I need one?", metrics: ["34%", "7m", "1"], packet: ["Intent: payment plan interest", "Tool: payment options FAQ", "Escalation: not required"] },
      { at: 33000, time: "0:33", scene: "Helpful answer",  who: "Riley · access agent", type: "agent",   text: "Yes, payment plans are arranged with the billing team. I\u2019ll capture that interest in the action packet so they reach out in your preferred window.", speak: true, metrics: ["50%", "10m", "1"], packet: ["Intent: payment plan interest", "Tool: capture preference", "Escalation: billing follow-up"] },
      { at: 45000, time: "0:45", scene: "Off-script ask",  who: "Patient",              type: "patient", text: "What happens next if the payer needs more info?", metrics: ["58%", "12m", "2"], packet: ["Intent: payer follow-up", "Tool: claim workflow lookup", "Escalation: not required"] },
      { at: 52000, time: "0:52", scene: "Workflow",          who: "Riley · access agent", type: "agent",   text: "The approved workflow has the team gather payer follow-up context and circle back. I\u2019ll prepare a billing review packet that includes your payment-plan interest.", speak: true, metrics: ["64%", "13m", "2"], packet: ["Intent: payer follow-up + payment plan", "Tool: prepare billing review packet", "Escalation: billing staff queue"] },
      { at: 62000, time: "1:02", scene: "Window",            who: "Patient",              type: "patient", text: "Could they call me tomorrow morning?", metrics: ["68%", "14m", "2"], packet: ["Intent: callback window", "Tool: capture preference", "Escalation: not required"] },
      { at: 68000, time: "1:08", scene: "Acknowledge",       who: "Riley · access agent", type: "agent",   text: "Yes, I\u2019ll request tomorrow between 9 and 11 AM. The team will see the full payer note and your interest in a payment plan.", speak: true, metrics: ["72%", "15m", "2"], packet: ["Intent: callback window confirmed", "Tool: callback preference", "Escalation: billing follow-up"] },
      { at: 78000, time: "1:18", scene: "Action trigger",   who: "System action",        type: "system",  text: "Action packet created: April 22 statement, payer follow-up reason, payment-plan interest, callback tomorrow 9\u201311 AM, approved script attached.", speak: true, metrics: ["75%", "16m", "2"], packet: ["Intent: billing review", "Tool: create staff task", "Escalation: billing queue prepared"], tag: "Ready" },
      { at: 86000, time: "1:26", scene: "Close",             who: "Riley · access agent", type: "agent",   text: "You\u2019re set, Alex. Voice AI can reduce revenue-cycle friction without exposing sensitive billing data.", speak: true, metrics: ["78%", "19m", "3"], packet: ["Outcome: exception-ready", "Risk: reduced data exposure", "Governance: portal sign-in"], tag: "Complete" }
    ]
  },
  multilingual: {
    label: "Multilingual access",
    title: "AI expands access capacity",
    summary: "Route language needs and prepare a human-ready summary.",
    hook: "The access story gets stronger when the patient needs help in another language and the system still routes safely.",
    close: "Access improves when AI handles routine language friction and hands complex needs to the right human team.",
    captions: ["Language access at the front door", "Structured summary for staff", "Human handoff preserved"],
    talkTrack: "Language access is an operational throughput issue and an equity issue. This demo shows multilingual routing, a structured staff summary, and safe escalation for complex needs.",
    systemPrompt: "You are Riley, a Northlake Health multilingual patient access voice agent demo. Be warm. Use approved demo data only. Acknowledge language preference, prepare a staff-ready language access summary, and route clinical translation or complex needs to certified language services.",
    script: [
      { at: 800,  time: "0:01", scene: "Greeting",         who: "Riley · access agent", type: "agent",   text: "Hola Elena, soy Riley con Northlake Health. I see your follow-up is Friday at 2:15 PM at Harborview Clinic. Would you like me to continue in Spanish?", speak: true, metrics: ["10%", "2m", "2"], packet: ["Intent: not detected yet", "Identity: portal sign-in", "Escalation: not required"] },
      { at: 6500, time: "0:07", scene: "Confirm need",     who: "Patient",              type: "patient", text: "Yes please - I just want to confirm the visit and what to bring.", metrics: ["14%", "3m", "2"], packet: ["Intent: appointment confirmation", "Tool: language preference detection", "Escalation: not required"] },
      { at: 12000, time: "0:12", scene: "Acknowledge",     who: "Riley · access agent", type: "agent",   text: "Of course. Friday at 2:15 PM with Dr. Romero, primary care follow-up. Plan to arrive by 2:00 PM and bring an updated medication list.", speak: true, metrics: ["24%", "5m", "2"], packet: ["Intent: confirmed visit + prep", "Tool: portal + FAQ", "Escalation: not required"] },
      { at: 22000, time: "0:22", scene: "Off-script ask",  who: "Patient",              type: "patient", text: "Could a family member be on the callback with me?", metrics: ["34%", "7m", "2"], packet: ["Intent: family on callback", "Tool: callback preference", "Escalation: not required"] },
      { at: 28500, time: "0:28", scene: "Helpful answer",  who: "Riley · access agent", type: "agent",   text: "Yes, that\u2019s welcome. I\u2019ll note that your daughter or another family member may join, so the team expects an extra voice.", speak: true, metrics: ["46%", "9m", "2"], packet: ["Intent: family-supported callback", "Tool: capture preference", "Escalation: not required"] },
      { at: 38000, time: "0:38", scene: "Detail",            who: "Patient",              type: "patient", text: "Sometimes I have a hard time understanding the instructions. Could there be an interpreter for the visit?", metrics: ["54%", "11m", "2"], packet: ["Intent: interpreter request", "Tool: language services FAQ", "Escalation: language services"] },
      { at: 45000, time: "0:45", scene: "Language route",   who: "Riley · access agent", type: "agent",   text: "Absolutely. I\u2019ll request a Spanish interpreter for the visit and add it to the action packet so the clinic team is ready.", speak: true, metrics: ["62%", "13m", "3"], packet: ["Intent: Spanish interpreter request", "Tool: language services route", "Escalation: language services"] },
      { at: 56000, time: "0:56", scene: "Concern",           who: "Patient",              type: "patient", text: "And one more thing - I\u2019m worried I may have missed an instruction from the last visit.", metrics: ["66%", "14m", "3"], packet: ["Intent: instruction concern", "Tool: capture for staff", "Escalation: clinical concerns route to staff"] },
      { at: 64000, time: "1:04", scene: "Safe guidance",    who: "Riley · access agent", type: "agent",   text: "I\u2019ll capture exactly what the instruction was about. Anything clinical or urgent I\u2019ll route to the care team right away.", speak: true, metrics: ["70%", "15m", "3"], packet: ["Intent: prep support", "Tool: approved instruction lookup", "Escalation: clinical concerns route to staff"] },
      { at: 75000, time: "1:15", scene: "Action trigger",   who: "System action",        type: "system",  text: "Action packet created: confirmed Friday 2:15 PM visit, Spanish interpreter requested, family on callback, instruction concern routed to staff.", speak: true, metrics: ["75%", "17m", "4"], packet: ["Intent: language access handoff", "Tool: create staff summary", "Escalation: language services-ready"], tag: "Ready" },
      { at: 84000, time: "1:24", scene: "Close",             who: "Riley · access agent", type: "agent",   text: "All set, Elena. Multilingual voice access can improve throughput while preserving human escalation.", speak: true, metrics: ["80%", "21m", "4"], packet: ["Outcome: language need routed", "Risk: no clinical translation claim", "Governance: portal sign-in + approved handoff"], tag: "Complete" }
    ]
  }
};
